[package]
name = "ARayTracingJourney"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[target.'cfg(target_feature = "avx")']
rustflags = ["-C target-feature=+adx,+sse,+sse2,+sse3,+sse4.1,+sse4.2,+fma,+cmpxchg16b,+bmi,+bmi2,+avx,+avx2"]

[profile.dev]
opt-level = 0
debug = true
split-debuginfo = '...'  # Platform-specific.
debug-assertions = true
overflow-checks = true
lto = false
panic = 'unwind'
incremental = true
codegen-units = 256
rpath = false

[profile.release]
opt-level = 3
debug = false
split-debuginfo = '...'  # Platform-specific.
debug-assertions = false
overflow-checks = false
lto = true
panic = 'unwind'
incremental = false
codegen-units = 8
rpath = false

[dependencies]
num = "0.4.0"
ash = "0.36.0"
winit = "0.26.1"
raw-window-handle = "0.4.2"
gpu-allocator = "0.17.0"
nalgebra = "0.30.1"
cfg-if = "1.0.0"
gltf = "1.0.0"
bitflags = "1.3.2"

[build-dependencies]
shaderc = "0.7.4"
