[package]
name = "ARayTracingJourney"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num = "0.4.0"
ash = "0.36.0"
winit = "0.26.1"
raw-window-handle = "0.4.2"
gpu-allocator = "0.17.0"
nalgebra = "0.30.1"
cfg-if = "1.0.0"

[build-dependencies]
shaderc = "0.7.4"
